# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Stop app
      continue-on-error: true
      run: fuser -k 8090/tcp
    - name: Git pull
      run: cd /opt/barsik/barsik && git pull origin master
      continue-on-error: true
    - name: Run
      run: cd /opt/barsik/barsik && mvn spring-boot:run
